names=input("Enter your name")
print(names)
print()

print("Good,Enter your goals for this project")
goals=input("what are the goals for this project?")
print(goals)
country=input("enter your country")
print(country)
country2=input("enter your country")
print(country2)
